var dummyData = [
  {
    id: 1,
    postedOn: new Date(),
    title: "Forntend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "Google.com",
    skills: ["Javascript", "React JS", "Node JS"],
    link: "https://google.com/careers",
  },
  {
    id: 1,
    postedOn: new Date(),
    title: "Forntend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "Google.com",
    skills: ["Javascript", "React JS", "Node JS"],
    link: "https://google.com/careers",
  },
  {
    id: 1,
    postedOn: new Date(),
    title: "Forntend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "Google.com",
    skills: ["Javascript", "React JS", "Node JS"],
    link: "https://google.com/careers",
  },
  {
    id: 1,
    postedOn: new Date(),
    title: "Forntend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "Google.com",
    skills: ["Javascript", "React JS", "Node JS"],
    link: "https://google.com/careers",
  },
  {
    id: 1,
    postedOn: new Date(),
    title: "Forntend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "Google.com",
    skills: ["Javascript", "React JS", "Node JS"],
    link: "https://google.com/careers",
  },
  {
    id: 1,
    postedOn: new Date(),
    title: "Forntend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    companyUrl: "Google.com",
    skills: ["Javascript", "React JS", "Node JS"],
    link: "https://google.com/careers",
  },
];

export default dummyData;
